name: Workflow to test local prepare-incremental-build

on:
  push:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        description: The architecture to build against, e.g x86_64, aarch64, s390x...
        default: x86_64
      toolchain_full:
        required: true
        type: string
        description: The toolchain and for llvm, its version, e.g gcc, llvm-15
        default: llvm-17
      runs_on:
        required: true
        type: string
        description: The runners to run the test on. This is a json string representing an array of labels.
        default: ubuntu-24.04
      kernel:
        required: true
        type: string
        description: The kernel to run the test against. For KPD this is always LATEST, which runs against a newly built kernel.
        default: LATEST
      kernel-repo:
        required: true
        type: string
        default: kernel-patches/bpf
      kernel-branch:
        required: true
        type: string
        default: bpf-next

jobs:
  test-job:
    name: Test prepare-incremental-build action
    runs-on: ${{ inputs.runs_on || 'ubuntu-24.04' }}
    timeout-minutes: 100
    env:
        ARCH: ${{ inputs.arch || 'x86_64' }}
        TOOLCHAIN_FULL: ${{ inputs.toolchain_full || 'llvm-17' }}
        KERNEL: ${{ inputs.kernel || 'LATEST' }}
        KERNEL_REPO: ${{ inputs.kernel-repo || 'kernel-patches/bpf' }}
        KERNEL_BRANCH: ${{ inputs.kernel-branch || 'bpf-next' }}
        REPO_ROOT: ${{ github.workspace }}/linux
        KBUILD_OUTPUT: kbuild-output
    steps:

      - uses: actions/checkout@v4
        name: Checkout libbpf/ci

      - uses: actions/checkout@v4
        name: Checkout kernel-patches/bpf
        with:
          fetch-depth: 5
          repository: kernel-patches/bpf
          path: ${{ env.REPO_ROOT }}

      - name: Run prepare-incremental-build action
        uses: ./prepare-incremental-build
        with:
          repo-root: ${{ env.REPO_ROOT }}
          base-branch: ${{ env.KERNEL_BRANCH }}
          arch: ${{ inputs.arch }}
          toolchain_full: ${{ inputs.toolchain_full }}
          kbuild-output: ${{ env.KBUILD_OUTPUT }}

      - name: Put something in KBUILD_OUTPUT to trigger caching
        shell: bash
        run: |
          mkdir -p $KBUILD_OUTPUT/path/to
          echo "$ARCH $TOOLCHAIN_FULL $KERNEL" > $KBUILD_OUTPUT/path/to/output.txt

